### PR TITLE
Add methods about user in auth-server

### PR DESCRIPTION
**Pull request by seedspirit**
I created methods that wraps APIs related to user and tokens.
Also fixed `HttpResponseHandler` error message parsing logic as `!response.body().string().isEmpty()` close response before parsing start

### CODE REVIEW

**Comment by namkyu1999** [comment]
can you resolve conflicts?

**Comment by seedspirit** [comment]
@namkyu1999 resolved conflict! Thanks 😊

**Comment by seedspirit** [comment]
@suyeon-jung-dev  @jemlog @somln Can you please take a look?

**Review by jemlog — APPROVED** [review]
LGTM

**Review by suyeon-jung-dev — APPROVED** [review]
Great work! 🚀

**Pull request merged**
